### ISSUE TITLE
tlds in domains.json is an error object.  Cannot .filter, unless it is an array. 

### ISSUE THREAD

**Issue by travenasty** [OAuth3/oauth3-cli#2]
I am in a broken state where the domains.json and domains.bak.json both contain the following:

```
> cat domains.json
{"updatedAt":1460140268396,"tlds":{"error":{"name":"TypeError","message":"Cannot read property 'toString' of undefined"}}}
```

tld-hints.js parses that JSON and expects the .tlds property to be an array to .filter against.. but throws an error: 
`Reason:  [TypeError: domains.tlds.filter is not a function]`

**Comment by coolaj86** [comment]
Hmm... I see on the server that we're getting a bad response from enom. I'll check on that real quick...

Probably my fault - a mismatched dependency from trying to move all the deps over into one node_modules folder.

**Comment by coolaj86** [comment]
Ugh... apparently it's a quantum particle. If I try to `console.log(resp.body)` it's undefined, but if I `console.log(resp)` I see that `body` is the expected xml string. I hate it when this kind of stuff happens... :-/

I'll have it fixed it a minute or two I suppose.

**Comment by coolaj86** [comment]
Fixed (it was a mismatched pairing of `bluebird` and `request` causing the response object to be an array instead of an object).

You need to rid yourself of the offending error object (and I need to find out why that saved successfully on the client instead of throwing an error):

``` bash
rm /usr/local/lib/node_modules/daplie-tools/node_modules/oauth3-cli/lib/domains.*json*
```
